/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "py_string.h"

std::string py_string::Greeter::greeting() {
    return std::string("Hello, World!");
}
