/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef PY_STRING_H
#define PY_STRING_H

#ifdef _WIN32
#define PY_STRING_EXPORT_FUNC __declspec(dllexport)
#else
#define PY_STRING_EXPORT_FUNC
#endif

#include <string>

namespace py_string {
    class Greeter {
        public:
        std::string PY_STRING_EXPORT_FUNC greeting();
    };
}

#endif
